services:
  backend:
    build:
      context: ./
      target: development-build
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    restart: 'unless-stopped'
    networks:
      - wiki-search
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db-data:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
    env_file:
      - .env
    networks:
      - wiki-search

networks:
  wiki-search:
    driver: bridge

volumes:
  npm_cache:
  node_modules:
  data:
    driver: local
